In [11]:
import decoupler as dc
import lamindb as ln
import pandas as pd

assert ln.setup.settings.instance.slug == "theislab/sc-best-practices"
ln.track()

→ loaded Transform('DzP6eCPLEwPr0001', key='gsea_pathway_dataset.ipynb'), re-started Run('DOvUgvz3A4powlzS') at 2026-08-09 17:25:19 UTC
→ notebook imports: decoupler==2.2.0 lamindb-core==2.7.0 pandas==2.3.3
• recommendation: to identify the notebook across renames, pass the uid: ln.track("DzP6eCPLEwPr")

Data downloads from Figshare only worked when performed manually via a web browser.
- 'kang.h5ad': https://figshare.com/ndownloader/files/34464122
- 'progeny.csv': https://figshare.com/ndownloader/files/38892066
- 'c2.cp.reactome.v7.5.1.symbols.gmt': https://figshare.com/ndownloader/files/35233771

# 25K PBMC data
Seems to be exactly the same as key="conditions/differential_gene_expression.h5ad".

# REACTOME

In [12]:
af = ln.Artifact(
    "c2.cp.reactome.v7.5.1.symbols.gmt",
    key="conditions/gsea_pathway/c2.cp.reactome.v7.5.1.symbols.gmt",
    description="A GMT file for the REACTOME pathways annotated in the C2 collection of MSigDB.",
).save()
af

→ returning artifact with same hash: Artifact(uid='vndUgwQqDDiCknp60000', key='conditions/gsea_pathway/c2.cp.reactome.v7.5.1.symbols.gmt', description='A GMT file for the REACTOME pathways annotated in the C2 collection of MSigDB.', suffix='.gmt', kind=None, otype=None, size=770046, hash='_Yw6GzHAVApclf8fkg32xg', n_files=None, n_observations=None, extra_data=None, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=91, schema_id=None, created_by_id=6, created_at=2026-07-17 12:57:57 UTC, is_locked=False, version_tag=None, is_latest=True); to track this artifact as an input, use: ln.Artifact.get()

Artifact(uid='vndUgwQqDDiCknp60000', key='conditions/gsea_pathway/c2.cp.reactome.v7.5.1.symbols.gmt', description='A GMT file for the REACTOME pathways annotated in the C2 collection of MSigDB.', suffix='.gmt', kind=None, otype=None, size=770046, hash='_Yw6GzHAVApclf8fkg32xg', n_files=None, n_observations=None, extra_data=None, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=91, schema_id=None, created_by_id=6, created_at=2026-07-17 12:57:57 UTC, is_locked=False, version_tag=None, is_latest=True)

# PROGENy

In [13]:
progeny = pd.read_csv("progeny.csv")
progeny

        source   target     weight       p_value
0     Androgen  TMPRSS2  11.490631  0.000000e+00
1     Androgen   NKX3-1  10.622551  2.200000e-44
2     Androgen   MBOAT2  10.472733  4.600000e-44
3     Androgen     KLK2  10.176186  1.944410e-40
4     Androgen     SARG  11.386852  2.790210e-40
...        ...      ...        ...           ...
1395       p53  CCDC150  -3.174527  7.396252e-13
1396       p53    LCE1A   6.154823  8.475458e-13
1397       p53    TREM2   4.101937  9.739648e-13
1398       p53     GDF9   3.355741  1.087433e-12
1399       p53    NHLH2   2.201638  1.651582e-12

[1400 rows x 4 columns]

In [14]:
af = ln.Artifact.from_dataframe(
    progeny, key="conditions/gsea_pathway/progeny.parquet"
).save()
af

→ returning artifact with same hash: Artifact(uid='ylftc2GLWOcgKdcS0000', key='conditions/gsea_pathway/progeny.parquet', description=None, suffix='.parquet', kind='dataset', otype='DataFrame', size=39851, hash='BK48HjL37YxiaQo3qKRP6Q', n_files=None, n_observations=1400, extra_data=None, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=91, schema_id=None, created_by_id=6, created_at=2026-07-17 13:42:53 UTC, is_locked=False, version_tag=None, is_latest=True); to track this artifact as an input, use: ln.Artifact.get()

Artifact(uid='ylftc2GLWOcgKdcS0000', key='conditions/gsea_pathway/progeny.parquet', description=None, suffix='.parquet', kind='dataset', otype='DataFrame', size=39851, hash='BK48HjL37YxiaQo3qKRP6Q', n_files=None, n_observations=1400, extra_data=None, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=91, schema_id=None, created_by_id=6, created_at=2026-07-17 13:42:53 UTC, is_locked=False, version_tag=None, is_latest=True)

## CollecTRI

In [15]:
collectri = dc.op.collectri(organism="human")
collectri

,source,target,weight,resources,references,sign_decision
0,MYC,TERT,1.0,DoRothEA-A;ExTRI;HTRI;NTNU.Curated;Pavlidis202...,10022128;10491298;10606235;10637317;10723141;1...,PMID
1,SPI1,BGLAP,1.0,ExTRI,10022617,default activation
2,SMAD3,JUN,1.0,ExTRI;NTNU.Curated;TFactS;TRRUST,10022869;12374795,PMID
3,SMAD4,JUN,1.0,ExTRI;NTNU.Curated;TFactS;TRRUST,10022869;12374795,PMID
4,STAT5A,IL2,1.0,ExTRI,10022878;11435608;17182565;17911616;22854263;2...,default activation
...,...,...,...,...,...,...
42985,NFKB,hsa-miR-143-3p,1.0,ExTRI,19472311,default activation
42986,AP1,hsa-miR-206,1.0,ExTRI;GEREDB;NTNU.Curated,19721712,PMID
42987,NFKB,hsa-miR-21,1.0,ExTRI,20813833;22387281,default activation
42988,NFKB,hsa-miR-224-5p,1.0,ExTRI,23474441;23988648,default activation
42989,AP1,hsa-miR-144-3p,1.0,ExTRI,23546882,default activation

In [16]:
af = ln.Artifact.from_dataframe(
    collectri, key="conditions/gsea_pathway/collectri.parquet"
).save()
af

→ returning artifact with same hash: Artifact(uid='mWp6FwTagFi1JKDN0000', key='conditions/gsea_pathway/collectri.parquet', description=None, suffix='.parquet', kind='dataset', otype='DataFrame', size=724064, hash='AaTHSoyZuDdk5m884BZdnw', n_files=None, n_observations=42990, extra_data=None, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=91, schema_id=None, created_by_id=6, created_at=2026-08-09 13:55:45 UTC, is_locked=False, version_tag=None, is_latest=True); to track this artifact as an input, use: ln.Artifact.get()

Artifact(uid='mWp6FwTagFi1JKDN0000', key='conditions/gsea_pathway/collectri.parquet', description=None, suffix='.parquet', kind='dataset', otype='DataFrame', size=724064, hash='AaTHSoyZuDdk5m884BZdnw', n_files=None, n_observations=42990, extra_data=None, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=91, schema_id=None, created_by_id=6, created_at=2026-08-09 13:55:45 UTC, is_locked=False, version_tag=None, is_latest=True)

# msvisium

In [17]:
adata = dc.ds.msvisium()
adata

AnnData object with n_obs × n_vars = 3839 × 14940
    obs: 'array_row', 'array_col', 'niches'
    uns: 'spatial'
    obsm: 'spatial'

In [18]:
af = ln.Artifact.from_anndata(adata, key="conditions/gsea_pathway/msvisium.h5ad").save()
af

→ returning artifact with same hash: Artifact(uid='Xdf5W51L3kUH94Od0000', key='conditions/gsea_pathway/msvisium.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=90856207, hash='OzeBmCGAc3Nr-N-pS9stQE', n_files=None, n_observations=3839, extra_data=None, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=118, schema_id=None, created_by_id=6, created_at=2026-08-09 16:43:13 UTC, is_locked=False, version_tag=None, is_latest=True); to track this artifact as an input, use: ln.Artifact.get()

Artifact(uid='Xdf5W51L3kUH94Od0000', key='conditions/gsea_pathway/msvisium.h5ad', description=None, suffix='.h5ad', kind='dataset', otype='AnnData', size=90856207, hash='OzeBmCGAc3Nr-N-pS9stQE', n_files=None, n_observations=3839, extra_data=None, branch_id=1, created_on_id=1, space_id=1, storage_id=1, run_id=118, schema_id=None, created_by_id=6, created_at=2026-08-09 16:43:13 UTC, is_locked=False, version_tag=None, is_latest=True)

In [19]:
ln.finish()

• please hit CMD + s to save the notebook in your editor .... still waiting .....
................ ✓
! cells [(0, 11)] were not run consecutively
→ finished Run('DOvUgvz3A4powlzS') after 47s at 2026-08-09 17:26:06 UTC
→ go to: https://lamin.ai/theislab/sc-best-practices/run/DOvUgvz3A4powlzS
→ to update your notebook from the CLI, run: lamin save /Users/luisheinzlmeier/Desktop/Repos/single-cell-best-practices-parallel/scripts/conditions/gsea_pathway_dataset.ipynb